---
- name: Create tenant policies for fabric1
  hosts: fabric1
  gather_facts: false
  connection: local
  any_errors_fatal: true
  module_defaults:
    group/cisco.aci.all:
      hostname: "{{ ansible_host }}"
      username: "{{ username }}"
      password: "{{ password }}"
      validate_certs: false
      use_ssl: true

  roles:
    - roles/tn-tenant
    - roles/tn-vrf
    - roles/tn-ap
    - roles/tn-bd
    - roles/tn-epg
