---
# tasks file for roles/ap-vlans

- name: Create Attacheable Entity Profile (infra:AttEntityP, infra:ProvAcc)
  cisco.aci.aci_aep:
    aep: "{{item.aep_name}}"
    description: "{{item.aep_description}}"
    infra_vlan: "{{item.aep_infra_vlan}}"
    state: "{{item.state}}"
  delegate_to: localhost
  when: aeps is defined
  loop: "{{aeps}}"

- name: Delete Attacheable Entity Profile (infra:AttEntityP, infra:ProvAcc)
  cisco.aci.aci_aep:
    aep: "{{item.aep_name}}"
    description: "{{item.aep_description}}"
    infra_vlan: "{{item.aep_infra_vlan}}"
    state: "{{item.state}}"
  delegate_to: localhost
  when: aeps is defined
  loop: "{{aeps}}"

- name: Bind the VLAN pool specific to the AEP (infra:RsDomP)
  cisco.aci.aci_aep_to_domain: &binding_present
    aep: "{{item.aep_name}}"
    domain: "{{item.domain_name}}"
    domain_type: "{{item.domain_type}}"
    state: "{{item.state}}"
  delegate_to: localhost
  loop: "{{aeps}}"
  when: aeps is defined
