---
# tasks file for roles/ap-vlans
# All tasks using Infra as Code

- name: Attacheable Entity Profile via Infra as Code (infra:AttEntityP, infra:ProvAcc)
  cisco.aci.aci_aep:
    aep: "{{item.aep_name}}"
    description: "{{item.aep_description}}"
    infra_vlan: "{{item.aep_infra_vlan}}"
    state: "{{item.state}}"
  delegate_to: localhost
  when: aeps is defined
  loop: "{{aeps}}"
  tags:
    - never
    - iac

- name: Bind the domain to the AEP (infra:RsDomP)
  cisco.aci.aci_aep_to_domain:
    aep: "{{item.aep_name}}"
    domain: "{{item.domain_name}}"
    domain_type: "{{item.domain_type}}"
    state: "{{item.state}}"
  delegate_to: localhost
  loop: "{{aeps}}"
  when: aeps is defined
  tags:
    - never
    - iac

# All tasks using Procedural

- name: Create Attacheable Entity Profile via Procedural (infra:AttEntityP, infra:ProvAcc)
  cisco.aci.aci_aep:
    aep: "{{item.aep_name}}"
    description: "{{item.aep_description}}"
    infra_vlan: "{{item.aep_infra_vlan}}"
    state: present
  delegate_to: localhost
  when: aeps is defined
  loop: "{{aeps}}"
  tags:
    - never
    - create

- name: Bind the VLAN pool specific to the AEP (infra:RsDomP)
  cisco.aci.aci_aep_to_domain:
    aep: "{{item.aep_name}}"
    domain: "{{item.domain_name}}"
    domain_type: "{{item.domain_type}}"
    state: present
  delegate_to: localhost
  when: aeps is defined
  loop: "{{aeps}}"
  tags:
    - never
    - create

- name: Remove Binding  VLAN pool specific to the AEP (infra:RsDomP)
  cisco.aci.aci_aep_to_domain:
    aep: "{{item.aep_name}}"
    domain: "{{item.domain_name}}"
    domain_type: "{{item.domain_type}}"
    state: absent
  delegate_to: localhost
  when: aeps is defined
  loop: "{{aeps}}"
  tags:
    - never
    - delete

- name: Delete Attacheable Entity Profile via Procedural (infra:AttEntityP, infra:ProvAcc)
  cisco.aci.aci_aep:
    aep: "{{item.aep_name}}"
    description: "{{item.aep_description}}"
    infra_vlan: "{{item.aep_infra_vlan}}"
    state: absent
  delegate_to: localhost
  when: aeps is defined
  loop: "{{aeps}}"
  tags:
    - never
    - delete
