---
# All tasks using Infra as Code

- name: Tenant via Infra as Code (fv:Tenant)
  cisco.aci.aci_tenant:
    tenant: "{{item.tenant}}"
    description: "{{item.description}}"
    state: "{{item.state}}"
  delegate_to: localhost
  when: tenants is defined
  loop: "{{tenants}}"
  tags:
    - never
    - iac
# All tasks using Procedural

- name: Create Tenant via Procedural (fv:Tenant)
  cisco.aci.aci_tenant:
    tenant: "{{item.tenant}}"
    description: "{{item.description}}"
    state: present
  delegate_to: localhost
  when: tenants is defined
  loop: "{{tenants}}"
  tags:
    - never
    - create

- name: Delete Tenant via Procedural (fv:Tenant)
  cisco.aci.aci_tenant:
    tenant: "{{item.tenant}}"
    description: "{{item.description}}"
    state: absent
  delegate_to: localhost
  when: tenants is defined
  loop: "{{tenants}}"
  tags:
    - never
    - delete
