---
- name: Create access policies for fabric1
  hosts: fabric1
  gather_facts: false
  connection: local
  any_errors_fatal: true
  module_defaults:
    group/cisco.aci.all:
      hostname: "{{ ansible_host }}"
      username: "{{ username }}"
      password: "{{ password }}"
      validate_certs: no
      use_ssl: yes

  roles:
    - roles/ap-aep
